### ISSUE TITLE
Can't find them on website, links to product pages broken

### ISSUE THREAD

**Issue by DiscordiaMatrix** [app-generator/static-site#1]
Are all your Eleventy products discontinued? I can't find them anywhere on the site and the links to the product pages are broken. I love how some of the demos look.

**Comment by app-generator** [comment]
Hello @DiscordiaMatrix 

Here is an updated starter built on top of soft UI & Prismic CMS. 

https://github.com/app-generator/eleventy-soft-ui-design

The new version of [AppSeed](https://appseed.us/) is powered by the [generator](https://appseed.us/generator/) and 11ty will be integrated at some point. Not sure when, tbh.

 Our resources and efforts are driven by the community requests and, unfortunately, 11ty was not so popular among our users. 

11ty is great, really great but the adoption seems stale. 

Let us know if you need support regarding the 11-Soft-UI.
In case of any issues, we will assist.

**Comment by DiscordiaMatrix** [comment]
Thank you so much! I'll try out Soft UI and I'll be sure to let you know if I run into any problems.

**Comment by app-generator** [comment]
🚀🚀
